/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "Business_entity_type" CASCADE CONSTRAINTS';
	EXECUTE IMMEDIATE 'DROP TABLE   "Sentiment_snapshot" CASCADE CONSTRAINTS';
	EXECUTE IMMEDIATE 'DROP TABLE   "Sentiment_type" CASCADE CONSTRAINTS';
	EXECUTE IMMEDIATE 'DROP TABLE   "Country" CASCADE CONSTRAINTS';
	EXECUTE IMMEDIATE 'DROP TABLE   "Sentiment_lookup" CASCADE CONSTRAINTS';
	EXECUTE IMMEDIATE 'DROP TABLE   "Client_status" CASCADE CONSTRAINTS';
	EXECUTE IMMEDIATE 'DROP TABLE   "Client" CASCADE CONSTRAINTS';
	EXECUTE IMMEDIATE 'DROP TABLE   "Business_entity" CASCADE CONSTRAINTS';
	EXECUTE IMMEDIATE 'DROP TABLE   "Sentiment_lookup_domain" CASCADE CONSTRAINTS';
	
	EXCEPTION WHEN OTHERS THEN NULL;
end;



--------------------------------------------------------------------------------

/* Create Tables */

CREATE TABLE  "Business_entity_type"
(	"BUSINESS_ENTITY_TYPE_CODE" NUMBER(8,2) NOT NULL,
	"BUSINESS_ENTITY_TYPE_NAME" VARCHAR2(150) NOT NULL);
	
CREATE TABLE  "Sentiment_snapshot"
(	"SENTIMENT_SNAPSHOT_ID" NUMBER(8,2) NOT NULL,
	"LOOKUP_ID" NUMBER(8,2) NOT NULL,
	"URL" VARCHAR2(1000) NOT NULL,
	"TITLE" VARCHAR2(255) NOT NULL,
	"SNAPSHOT_DATETIME" TIMESTAMP(6) NOT NULL,
	"SENTIMENT_SNAPSHOT_RANK" NUMBER(8,2) NOT NULL,
	"SENTIMENT_LOOKUP_DOMAIN_CODE" NUMBER(8,2) NULL,
	"TRUST_LEVEL" FLOAT(50) NOT NULL,
	"SENTIMENT_TYPE_CODE" CHAR(3) NULL);

CREATE TABLE  "Sentiment_type"
(	"SENTIMENT_TYPE_CODE" CHAR(3) DEFAULT NEU NOT NULL,    -- Values: NEU, POS, NEG
	"SENTIMENT_TYPE_NAME" VARCHAR2(150) NULL);
	
CREATE TABLE  "Country"
(	"COUNTRY_CODE" CHAR(3) NOT NULL,
	"COUNTRY_NAME" VARCHAR2(200) NOT NULL) ;
	
CREATE TABLE  "Sentiment_lookup"
(	"LOOKUP_ID" NUMBER(8,2) NOT NULL,
	"LOOKUP_DATETIME" TIMESTAMP(6) NOT NULL,
	"BUSINESS_ENTITY_ID" NUMBER(8,2) NOT NULL,
	"CLIENT_ID" NUMBER(8,2) NOT NULL,
	"SENTIMENT_TYPE_CODE" CHAR(3) NULL);
	
CREATE TABLE  "Client_status"
(	"CLIENT_STATUS_CODE" NUMBER(8,2) NOT NULL,
	"CLIENT_STATUS_NAME" VARCHAR2(150) NOT NULL);
	
CREATE TABLE  "Client"
(	"CLIENT_ID" NUMBER(8,2) NOT NULL,
	"E_MAIL" VARCHAR2(255) NOT NULL,
	"FIRST_NAME" VARCHAR2(255) NOT NULL,
	"LAST_NAME" VARCHAR2(255) NULL,
	"AGREES_TO_DIRECT_MARKETING" NUMBER(1) DEFAULT 1 NOT NULL,    -- 1 OR 0
	"CLIENT_STATUS_CODE" NUMBER(8,2) NOT NULL,
	"COUNTRY_CODE" CHAR(3) NOT NULL);
	
CREATE TABLE  "Business_entity"
(	"BUSINESS_ENTITY_ID" NUMBER(8,2) NOT NULL,
	"BUSINESS_ENTITY_NAME" VARCHAR2(100) NOT NULL,
	"COUNTRY_CODE" CHAR(3) NULL);
	
CREATE TABLE  "Sentiment_lookup_domain"
(	"SENTIMENT_LOOKUP_DOMAIN_CODE" NUMBER(8,2) NOT NULL,
	"SENTIMENT_LOOKUP_DOMAIN_NAME" VARCHAR2(150) NOT NULL);
	
--------------------------------------------------------------------------------

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "Business_entity_type" 
 ADD CONSTRAINT "PK_BUSINESS_ENTITY_TYPE"
	PRIMARY KEY ("BUSINESS_ENTITY_TYPE_CODE")
 USING INDEX;
 
ALTER TABLE  "Sentiment_snapshot" 
 ADD CONSTRAINT "PK_SENTIMENT_SNAPSHOT"
	PRIMARY KEY ("SENTIMENT_SNAPSHOT_ID")
 USING INDEX;

CREATE INDEX "IXFK_SENTIMENT_SNAPSHOT_SENTIMENT_LOOKUP"   
 ON  "Sentiment_snapshot" ("LOOKUP_ID") ;

CREATE INDEX "IXFK_SENTIMENT_SNAPSHOT_SENTIMENT_LOOKUP_DOMAIN"   
 ON  "Sentiment_snapshot" ("SENTIMENT_LOOKUP_DOMAIN_CODE") ;

CREATE INDEX "IXFK_SENTIMENT_SNAPSHOT_SENTIMENT_TYPE"   
 ON  "Sentiment_snapshot" ("SENTIMENT_TYPE_CODE") ;
 
ALTER TABLE  "Sentiment_type" 
 ADD CONSTRAINT "PK_SENTIMENT_TYPE"
	PRIMARY KEY ("SENTIMENT_TYPE_CODE")
 USING INDEX;

ALTER TABLE  "Country" 
 ADD CONSTRAINT "PK_COUNTRY "
	PRIMARY KEY ("COUNTRY_CODE")
 USING INDEX;
	
ALTER TABLE  "Sentiment_lookup" 
 ADD CONSTRAINT "PK_SENTIMENT_LOOKUP "
	PRIMARY KEY ("LOOKUP_ID") 
 USING INDEX;

CREATE INDEX "IXFK_SENTIMENT_LOOKUP_BUSINESS_ENTITY"   
 ON  "Sentiment_lookup" ("BUSINESS_ENTITY_ID") ;

CREATE INDEX "IXFK_SENTIMENT_LOOKUP_CLIENT "   
 ON  "Sentiment_lookup" ("CLIENT_ID") ;

CREATE INDEX "IXFK_SENTIMENT_LOOKUP_SENTIMENT_TYPE"   
 ON  "Sentiment_lookup" ("SENTIMENT_TYPE_CODE") ;

ALTER TABLE  "Client_status" 
 ADD CONSTRAINT "PK_CLIENT_STATUS"
	PRIMARY KEY ("CLIENT_STATUS_CODE") 
 USING INDEX;
 
ALTER TABLE  "Client" 
 ADD CONSTRAINT "PK_CLIENT "
	PRIMARY KEY ("CLIENT_ID") 
 USING INDEX;

CREATE INDEX "IXFK_CLIENT_CLIENT_STATUS "   
 ON  "Client" ("CLIENT_STATUS_CODE") ;

CREATE INDEX "IXFK_CLIENT_COUNTRY "   
 ON  "Client" ("COUNTRY_CODE") ;
 
ALTER TABLE  "Business_entity" 
 ADD CONSTRAINT "PK_BUSINESS_ENTITY"
	PRIMARY KEY ("BUSINESS_ENTITY_ID") 
 USING INDEX;

CREATE INDEX "IXFK_BUSINESS_ENTITY_COUNTRY "   
 ON  "Business_entity" ("COUNTRY_CODE") ;
 
ALTER TABLE  "Sentiment_lookup_domain" 
 ADD CONSTRAINT "PK_SENTIMENT_LOOKUP_DOMAIN"
	PRIMARY KEY ("SENTIMENT_LOOKUP_DOMAIN_CODE") 
 USING INDEX; 
 
------------------------------------------------------------------------------ 
 
/* Create Foreign Key Constraints */

ALTER TABLE  "Sentiment_snapshot" 
 ADD CONSTRAINT "FK_SENTIMENT_SNAPSHOT_SENTIMENT_LOOKUP"
	FOREIGN KEY ("LOOKUP_ID") REFERENCES  "Sentiment_lookup" ("LOOKUP_ID");
	
ALTER TABLE  "Sentiment_snapshot" 
 ADD CONSTRAINT "FK_SENTIMENT_SNAPSHOT_SENTIMENT_LOOKUP_DOMAIN"
	FOREIGN KEY ("SENTIMENT_LOOKUP_DOMAIN_CODE")
		REFERENCES  "Sentiment_lookup_domain" ("SENTIMENT_LOOKUP_DOMAIN_CODE");

ALTER TABLE  "Sentiment_snapshot" 
 ADD CONSTRAINT "FK_SENTIMENT_SNAPSHOT_SENTIMENT_TYPE"
	FOREIGN KEY ("SENTIMENT_TYPE_CODE")
		REFERENCES "Sentiment_type" ("SENTIMENT_TYPE_CODE");	

ALTER TABLE  "Sentiment_lookup" 
 ADD CONSTRAINT "FK_SENTIMENT_LOOKUP_BUSINESS_ENTITY"
	FOREIGN KEY ("BUSINESS_ENTITY_ID") 
		REFERENCES  "Business_entity" ("BUSINESS_ENTITY_ID");

ALTER TABLE  "Sentiment_lookup" 
 ADD CONSTRAINT "FK_SENTIMENT_LOOKUP_CLIENT "
	FOREIGN KEY ("CLIENT_ID") REFERENCES  "Client" ("CLIENT_ID");

ALTER TABLE  "Sentiment_lookup" 
 ADD CONSTRAINT "FK_SENTIMENT_LOOKUP_SENTIMENT_TYPE"
	FOREIGN KEY ("SENTIMENT_TYPE_CODE") 
		REFERENCES  "Sentiment_type" ("SENTIMENT_TYPE_CODE");

ALTER TABLE  "Client" 
 ADD CONSTRAINT "FK_CLIENT_CLIENT_STATUS "
	FOREIGN KEY ("CLIENT_STATUS_CODE")
		REFERENCES  "Client_status" ("CLIENT_STATUS_CODE");

ALTER TABLE  "Client" 
 ADD CONSTRAINT "FK_CLIENT_COUNTRY "
	FOREIGN KEY ("COUNTRY_CODE") 
		REFERENCES  "Country" ("COUNTRY_CODE");
		
ALTER TABLE  "Business_entity" 
 ADD CONSTRAINT "FK_BUSINESS_ENTITY_COUNTRY "
	FOREIGN KEY ("COUNTRY_CODE") REFERENCES  "Country" ("COUNTRY_CODE");







		
	
	
	